# Generated by Django 5.0.1 on 2024-08-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recover_code',
        ),
    ]
