# Generated by Django 5.0.1 on 2024-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_question_answer_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='questions/diagrams/'),
        ),
    ]
