# Generated by Django 5.0.1 on 2024-08-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_suffle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject'),
        ),
    ]
