# Generated by Django 5.0.1 on 2024-08-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_userprofile_number_of_questions_userprofile_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suffle',
            name='user',
        ),
    ]
