# Generated by Django 5.0.1 on 2024-08-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_suffle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='suffle',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
