# Generated by Django 5.0.1 on 2024-08-19 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_examsession'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
