# Generated by Django 5.0.1 on 2024-08-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_examsession_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='user',
        ),
    ]
