# Generated by Django 5.0.1 on 2024-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_examsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
