# Generated by Django 5.0.1 on 2024-08-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_examsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='shuffle_order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
