# Generated by Django 5.0.1 on 2024-08-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_examsession_shuffle_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_duration',
            field=models.CharField(default='01:00:00', max_length=8),
        ),
    ]
