# Generated by Django 5.0.1 on 2024-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_user_result_correct_answers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=345)),
            ],
        ),
    ]
