# Generated by Django 5.0.1 on 2024-08-27 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_userid_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_duration',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_start_time',
            field=models.DateTimeField(),
        ),
    ]
