# Generated by Django 5.0.1 on 2024-08-27 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_examsession_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userid',
            name='session_id',
        ),
        migrations.AddField(
            model_name='examsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examsession',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_duration',
            field=models.CharField(default='01:00:00', max_length=8),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
