# Generated by Django 5.0.1 on 2024-08-27 01:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_examsession_user_remove_userid_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.examsession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
