# Generated by Django 5.0.1 on 2024-08-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_userexamsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='session_id',
        ),
    ]
