# Generated by Django 5.0.1 on 2024-08-27 11:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_userexamsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='session_id',
        ),
        migrations.CreateModel(
            name='UserExamSessionx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.examsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.DeleteModel(
            name='UserExamSession',
        ),
    ]
