# Generated by Django 5.0.1 on 2024-08-27 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_examsession_session_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexamsession',
            unique_together={('user', 'is_active')},
        ),
        migrations.AddField(
            model_name='userexamsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userexamsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userexamsession',
            name='exam_session',
        ),
    ]
