# Generated by Django 5.0.1 on 2024-08-27 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_userexamsession_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexamsession',
            old_name='is_active',
            new_name='actives',
        ),
        migrations.AlterUniqueTogether(
            name='userexamsession',
            unique_together=set(),
        ),
    ]
