# Generated by Django 5.0.1 on 2024-08-27 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_is_active_userexamsession_actives_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexamsession',
            name='actives',
        ),
        migrations.AddField(
            model_name='userexamsession',
            name='exam_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.examsession'),
        ),
        migrations.AlterField(
            model_name='userexamsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
