# Generated by Django 5.0.1 on 2024-08-30 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_loding_remove_result_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='loding',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
