# Generated by Django 5.0.1 on 2024-08-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_classorlevel_termorsemester_alter_question_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='term_or_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.termorsemester'),
        ),
        migrations.AddField(
            model_name='termorsemester',
            name='class_or_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.classorlevel'),
        ),
        migrations.AlterField(
            model_name='termorsemester',
            name='name',
            field=models.CharField(choices=[('first_term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('first_semester', 'First Semester'), ('second_semester', 'Second Semester'), ('general exam', 'General Exam')], max_length=20),
        ),
    ]
