# Generated by Django 5.0.1 on 2024-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_subject_term_or_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='termorsemester',
            name='name',
            field=models.CharField(choices=[('First Term', 'First Term'), ('second_term', 'Second Term'), ('third_term', 'Third Term'), ('first_semester', 'First Semester'), ('second_semester', 'Second Semester'), ('general exam', 'General Exam')], max_length=20),
        ),
    ]
