# Generated by Django 5.0.1 on 2024-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_subject_name_alter_termorsemester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classorlevel',
            name='name',
            field=models.CharField(choices=[('jss1', 'JSS 1'), ('jss2', 'JSS 2'), ('jss3', 'JSS 3'), ('sss1', 'SSS 1'), ('sss2', 'SSS 2'), ('sss3', 'SSS 3'), ('cbt', 'CBT'), ('level 100', 'Level 100'), ('level 200', 'Level 200'), ('level 300', 'Level 300'), ('level 400', 'Level 400')], max_length=20),
        ),
        migrations.AlterField(
            model_name='termorsemester',
            name='name',
            field=models.CharField(choices=[('First Term', 'First Term'), ('second term', 'Second Term'), ('third term', 'Third Term'), ('first semester', 'First Semester'), ('second semester', 'Second Semester'), ('general exam', 'General Exam')], max_length=20),
        ),
    ]
