# Generated by Django 5.0.1 on 2024-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_classorlevel_name_alter_termorsemester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
