# Generated by Django 5.0.1 on 2024-09-03 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_user_session_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexamsessionx',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='paused_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='remaining_time_when_paused',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='userexamsessionx',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
