# Generated by Django 5.0.1 on 2024-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_userexamsessionx_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexamsessionx',
            old_name='remaining_time_when_paused',
            new_name='remaining_time',
        ),
        migrations.RemoveField(
            model_name='userexamsessionx',
            name='paused',
        ),
    ]
