# Generated by Django 5.0.1 on 2024-09-04 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_remaining_time_when_paused_userexamsessionx_remaining_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexamsessionx',
            unique_together={('user', 'subject')},
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userexamsessionx',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='userexamsessionx',
            name='paused_time',
        ),
        migrations.RemoveField(
            model_name='userexamsessionx',
            name='remaining_time',
        ),
    ]
