# Generated by Django 5.0.1 on 2024-09-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_classorlevel_name_alter_termorsemester_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userexamsessionx',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='paused_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexamsessionx',
            name='remaining_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userexamsessionx',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
