# Generated by Django 5.0.1 on 2024-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_userexamsessionx_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termorsemester',
            name='name',
            field=models.CharField(choices=[('First Term', 'First Term'), ('second term', 'Second Term'), ('third term', 'Third Term'), ('first semester', 'First Semester'), ('second semester', 'Second Semester'), ('general exam', 'General Exam'), (' Test 1', 'Test 1'), (' Test 2', 'Test 2'), (' Test 3', 'Test 3')], max_length=20),
        ),
    ]
