# Generated by Django 5.0.1 on 2024-09-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_endx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userid',
            name='generated_id',
        ),
        migrations.AddField(
            model_name='userid',
            name='class_name',
            field=models.CharField(choices=[('jss1', 'JSS 1'), ('jss2', 'JSS 2'), ('jss3', 'JSS 3'), ('sss1', 'SSS 1'), ('sss2', 'SSS 2'), ('sss3', 'SSS 3'), ('cbt', 'CBT'), ('Test', 'Test'), ('level 100', 'Level 100'), ('level 200', 'Level 200'), ('level 300', 'Level 300'), ('level 400', 'Level 400')], max_length=20, null=True),
        ),
    ]
