# Generated by Django 5.0.1 on 2024-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_userid_generated_id_userid_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='generated_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
